spring:
  security:
    oauth2:
      client:
        registration:
          uaa-none:
            provider: uaa
            client-id: login
            client-authentication-method: none
            authorization-grant-type: authorization_code
            client-name: "Public (none) client usage (authentication)"
            scope:
              - openid
          uaa-pkj:
            provider: uaa
            client-id: login
            client-authentication-method: private_key_jwt
            authorization-grant-type: authorization_code
            client-name: "Private_key_jwt client authentication"
            scope:
              - openid
        provider:
          uaa:
            issuer-uri: http://localhost:8080/uaa/oauth/token
welcome:
  message: Welcome to Spring UAA example

appconfig:
  appurl: http://localhost:7000
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIE7gIBADA9BgkqhkiG9w0BAQowMKANMAsGCWCGSAFlAwQCAaEaMBgGCSqGSIb3
    DQEBCDALBglghkgBZQMEAgGiAwIBIASCBKgwggSkAgEAAoIBAQDsqXF2VINXR19I
    7ZkvTulB+AZrnv6VbHeDf6gHZGur/O8gLIOBi/qL2JXKLA7SziiK85sB5ARPx/sA
    ElIDfREKZRf9wtzwEIpQfUwPwju1/tSu/s7p4Yc/wlw0f1HWhsK8poaAA/J00dMy
    XVJ4EGDGF1zxOITYxj+GxJpRv3Iy17whSfYtutRpIK/TY4rh0dur0Kdj2Xw/+ayY
    7pY3aLpxerfpZn00H83kaJhfSpkTc6zPkvKENp3MwMRVbxZTISDwmOYpEsLd6Hp8
    KlKIGQL+8H3V9UCB6S4fl2p4n8OX2mmQNTrlp13F7WdjZWntVZ6DrqWtAg5WRMRj
    B5f8J5gNAgMBAAECggEBAIPT1woNBaRmc2NSRpQdpr1ChYEJbdKaOvCa+WQ0we1p
    1WHcqdxNtuCTYszdQdyXTeoozF1/QA+Y2+4sRlb/IbDiozyNgTiQXht70BSvI0e7
    jYl1EpkhMY+Imof7rACNzIf9UsqYaEQ+ZSCW70tGBEIT3YfY7dc6h0Rw221R8TDz
    /PN/cSVolNBRW4DP1TnYTZ+6Tl1Z+08zSRPLwiX6ghcoLz91d8Q/xwLdxD88eTsM
    s1JPKsgIwht5AS9OIJlbLlrbc05VxuaTpuhX0P/SVtjvMxVBkxpHGOGShV51dpak
    z7XEl1B2IlnPVVeA21spNeQCplNePnNo8SFfQHPra1kCgYEA9/owW6q4Znfs1vnM
    K/hzR3asrnof/ziZK/FR+CLKhSFiex+uUpg3mLNpVycQ8zs0Eigy2I+T0yu9KoHu
    Tgm72ne/CPDFbISHZse30OTHZsBiKNamC4u99VAKWt/cUtXsVERMBRO+RsARyGpX
    FF3tq/flpVBOH/4iDn+1iTWJ+W8CgYEA9FGJhO9pTUysSCNMPPHxLER01yECUOlf
    hNOd3bpum0qqP/XLlSVFolSEZrOgfZT/pagLkIPrYmgpnkizmJAcldNl/NkXmTfi
    J0xHIaOFEE6dSFuFD4svHN45t5xHJItgacssLCY4HZnd7VM//bT2FZmm9c0U+M82
    fwFuAs3hsEMCgYBB1Xs3KujP03DeVe0dk1VPmLMZkzShdm4721JutRXdKFLT60JF
    jUHdWWxTBf0bBhG57FArbFrLimYrPdl9gFoOExJ1li5js/+aitVDMSm7HsIwo2Pr
    1sq0sO4+2AXPPBoE+SjRhD9U2zMdaRX7Q0CREjw2mk5Tcg2qmb8hUURzIwKBgQC+
    nRrYr10NpQNI6NkjN3P9II+0BBnlfJ48aEnjYv/GgrNfYWprO4AfjScbZYuSTvxB
    h2E2Z+XuievmhTwxjEXxEtSgN9O0g6gbFuTsNsKrHVqSyGyA2wtvz2Vifjf3KBKZ
    l50n+M2RMqm17lyfmV7hLVbYsR9qm2geIMRuxagONwKBgDF97VjqxcZpr7TOAZyW
    RNo12UXJjqhUsLgKlU5FaqDlDRy+h3PzARfYUmnYcv/PcVjCq8CcU/RWRxqwiwNL
    pZhxwdKr20/lMjbgt0rNrVoVLApE0K+agEveAFflZFmouLmIoKiDgpkwLptCQ6fB
    x7Ap6BqiLdDqgvdLVbtv578b
    -----END PRIVATE KEY-----
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIEFzCCAs+gAwIBAgIUFnLU0GLwRzvQBeGQBNOY+1fuUIswPQYJKoZIhvcNAQEK
    MDCgDTALBglghkgBZQMEAgGhGjAYBgkqhkiG9w0BAQgwCwYJYIZIAWUDBAIBogMC
    ASAwUzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkJXMQwwCgYDVQQKDANTQVAxDDAK
    BgNVBAMMA0pXVDEbMBkGCSqGSIb3DQEJARYMdGVzdEBzYXAuY29tMB4XDTIzMDEy
    ODEwNTE0M1oXDTI0MDEyMzEwNTE0M1owUzELMAkGA1UEBhMCVVMxCzAJBgNVBAgM
    AkJXMQwwCgYDVQQKDANTQVAxDDAKBgNVBAMMA0pXVDEbMBkGCSqGSIb3DQEJARYM
    dGVzdEBzYXAuY29tMIIBUjA9BgkqhkiG9w0BAQowMKANMAsGCWCGSAFlAwQCAaEa
    MBgGCSqGSIb3DQEBCDALBglghkgBZQMEAgGiAwIBIAOCAQ8AMIIBCgKCAQEA7Klx
    dlSDV0dfSO2ZL07pQfgGa57+lWx3g3+oB2Rrq/zvICyDgYv6i9iVyiwO0s4oivOb
    AeQET8f7ABJSA30RCmUX/cLc8BCKUH1MD8I7tf7Urv7O6eGHP8JcNH9R1obCvKaG
    gAPydNHTMl1SeBBgxhdc8TiE2MY/hsSaUb9yMte8IUn2LbrUaSCv02OK4dHbq9Cn
    Y9l8P/msmO6WN2i6cXq36WZ9NB/N5GiYX0qZE3Osz5LyhDadzMDEVW8WUyEg8Jjm
    KRLC3eh6fCpSiBkC/vB91fVAgekuH5dqeJ/Dl9ppkDU65addxe1nY2Vp7VWeg66l
    rQIOVkTEYweX/CeYDQIDAQABo1MwUTAdBgNVHQ4EFgQUaA9pTv4WcnOQuFb8dDsH
    izii9c0wHwYDVR0jBBgwFoAUaA9pTv4WcnOQuFb8dDsHizii9c0wDwYDVR0TAQH/
    BAUwAwEB/zA9BgkqhkiG9w0BAQowMKANMAsGCWCGSAFlAwQCAaEaMBgGCSqGSIb3
    DQEBCDALBglghkgBZQMEAgGiAwIBIAOCAQEAzHGyO47zfnLFdFrxxF36q/rRfyfZ
    da8lC6wy6/lvYbvjZjcrJ8ee3kw8vSSyBsZNxMVh1D2NSYBOlcQhnNQJxBD/cDSk
    BwXougGckdabK5/5OB5H8YQoAD2Wf/hoyNkUQzYP4ZjXyNZLA5LiKwO1DM1JnlWc
    wbvCZ4anZIehjJclvANI9wUM0Z1VLt4wwhM+VxCo/ht/DkHEzmLryjFNd/UE9nT9
    QkO8o9njUGPZ4krYC56UjuHBKx83tEKpbu25/FnaiGOIJnP/CRGi7tOfZ2S5B0Et
    r8HvlqzoFqksSPNJNpqgFqhT2NSFkQA4EroduXWpT8Ag6x09fdrSTCOPmQ==
    -----END CERTIFICATE-----
